import Base
import ./LAWS.bend as L

def L.encode_empty():
  {==}

def L.decode_empty():
  {==}

def L.encode_golden():
  {==}

def L.decode_golden():
  {==}

def L.encode_aa():
  {==}

def L.decode_aa():
  {==}

def L.decode_FF():
  {==}

def L.nibble_0():
  {==}

def L.nibble_f():
  {==}

def L.nibble_F():
  {==}

def L.nibble_g():
  {==}

def L.b64_encode_empty():
  {==}

def L.b64_decode_empty():
  {==}

def L.b64_encode_golden():
  {==}

def L.b64_decode_golden():
  {==}

def L.b64url_encode_golden():
  {==}

def L.utf8_empty():
  {==}

def L.utf8_A():
  {==}
